### ISSUE TITLE
use "singular to plural" pronouns -- typo?

### ISSUE THREAD

**Issue by tnguyen-rh** [daobrien/WritingStyleGuide#6]
In section 2.2 Agreement, immediately following heading "Collective nouns.", there is the sentence:

    Rule: When collective nouns are used as antecedents, use singular to plural pronouns, depending on the sentence's meaning. 

I don't understand "singular to plural" however.  Is that a typo?  What am i missing?

**Comment by daobrien** [comment]
Yes, it should be "or".

Thanks for picking it up. I'll get it fixed.

Regards,
David


On Wed, Jun 3, 2015 at 1:35 AM, Thien-Thi Nguyen <notifications@github.com>
wrote:

> In section 2.2 Agreement, immediately following heading "Collective
> nouns.", there is the sentence:
>
> Rule: When collective nouns are used as antecedents, use singular to plural pronouns, depending on the sentence's meaning.
>
> I don't understand "singular to plural" however. Is that a typo? What am i
> missing?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/daobrien/WritingStyleGuide/issues/6>.
>



-- 
/David

**Comment by tnguyen-rh** [comment]
Hi David,

> Yes, it should be "or".
> 
> Thanks for picking it up. I'll get it fixed.

Cool, thanks.

Regards,
Thien-Thi

**Comment by daobrien** [comment]
I fixed the typo, patched up some of the xml, and clarified some of the text. New version published.
